version: "3"

networks:
       frontend:

services:

      mvc:
        build:
          context: .
          dockerfile: Dockerfile
        container_name: AppMvc
        networks:
          - frontend
        ports:
          - 5000:80   